### ISSUE TITLE
Can we simplify this query?

### ISSUE THREAD

**Issue by omid** [casbin-rs/diesel-adapter#14]
We have a query [here](https://github.com/casbin-rs/diesel-adapter/blob/3f0c99f3a0cd76060b8b8d8d154ad4314a0b07b5/src/databases/postgresql.rs#L48).

Cannot we simplify it to the following code? If not why not, I cannot see the difference :-(

```
diesel::delete(
        casbin_rules.filter(
            ptype
                .eq(pt)
                .and(v0.is_not_distinct_from(rule.get(0)))
                .and(v1.is_not_distinct_from(rule.get(1)))
                .and(v2.is_not_distinct_from(rule.get(2)))
                .and(v3.is_not_distinct_from(rule.get(3)))
                .and(v4.is_not_distinct_from(rule.get(4)))
                .and(v5.is_not_distinct_from(rule.get(5)))
        )
    )
```

**Comment by GopherJ** [comment]
Sure we can.

**Comment by GopherJ** [comment]
I already refactored this and I'll push after finishing the updates for casbin@0.3.0

**Comment by GopherJ** [comment]
@omid could you help reviewing #15 , thanks!
