### ISSUE TITLE
Can we override the table name and column name

### ISSUE THREAD

**Issue by xcaptain** [casbin-rs/diesel-adapter#17]
I have an old project which holds policies in a table named `casbin_rule` and with a column named `p_type`, I found in the project the default table name is `casbin_rules` and column name `ptype`, can we provide some mechanism to map between the model and table so I don't need to alter my database table?

@GopherJ

**Comment by xcaptain** [comment]
Also can we override the column constraint? for example, I have 

```
v0 VARCHAR
``` 
while the default behavior is 
```
v0 VARCHAR NOT NULL
```

**Comment by GopherJ** [comment]
@xcaptain the table name can only be hard coded in diesel. That's the root cause actually.

For the constraint, I think it's better to have `NOT NULL` because that make `Unique Constraint` works. Otherwise if we have both nullable and non-nullable values, the unique constraint will not work.

One solution for solving your first issue is to let diesel-adapter use existing table and database.

The second I think we shouldn't touch maybe? Do you have some advices?

**Comment by xcaptain** [comment]
Too bad diesel doesn't support column name mapping, then can we pass table name as parameter so we can use different table names?

**Comment by GopherJ** [comment]
@xcaptain  as you can see it's hard coded here, but actually we can maybe use proc-macro to generate this declaration

**Comment by GopherJ** [comment]
@xcaptain you can maybe use a forked version then we see how to solve this. That's easier.

Like I used to do, creating a directory `third-party` then `git clone` this repo.

And use in Cargo.toml

```toml
diesel-adapter = { version = "0.3.1", path = "third-party/diesel-adapter" }
``

**Comment by xcaptain** [comment]
@GopherJ This seems like a hard problem, I will try clone and modify the source by myself. I don't think a proc_macro would help, diesel's schema definitions were determined at compile time, we can't pass in a proc_macro from user code to library.

**Comment by GopherJ** [comment]
@xcaptain check maybe also this because a student is working on sqlx-adapter

https://github.com/casbin-rs/sqlx-adapter/pulls

**Comment by hsluoyz** [comment]
@GopherJ @xcaptain actually Golang's Xorm Adapter should be regarded as the standard: https://github.com/casbin/xorm-adapter/blob/master/adapter.go#L29

```go
// TableName  if tableName=="" , adapter will use default tablename "casbin_rule".
func (the *CasbinRule) TableName() string {
	if len(the.tableName) == 0 {
		return "casbin_rule"
	}
	return the.tableName
}

// CasbinRule  .
type CasbinRule struct {
	PType string `xorm:"varchar(100) index not null default ''"`
	V0    string `xorm:"varchar(100) index not null default ''"`
	V1    string `xorm:"varchar(100) index not null default ''"`
	V2    string `xorm:"varchar(100) index not null default ''"`
	V3    string `xorm:"varchar(100) index not null default ''"`
	V4    string `xorm:"varchar(100) index not null default ''"`
	V5    string `xorm:"varchar(100) index not null default ''"`

	tableName string `xorm:"-"`
}
```

So the default table name should be "casbin_rule", and the default first column name should be "p_type".

We should change these default values. It would be great if we can also support customizing those names.

**Comment by hsluoyz** [comment]
@MATRIXKOO can you make a PR to fix these default values?

**Comment by MATRIXKOO** [comment]
I take this.

**Comment by MATRIXKOO** [comment]
I have tried to support customizing names but failed. Now I just simple modified `casbin_rules` to `casbin_rule`  and `ptype` to `p_type`.

**Comment by hsluoyz** [comment]
@MATRIXKOO that's fine. Plz make a PR.

**Comment by MATRIXKOO** [comment]
I just fix the table name.

**Comment by hsluoyz** [comment]
We can fix both in one PR.

**Comment by hsluoyz** [comment]
casbin_rules -> casbin_rule done: https://github.com/casbin-rs/diesel-adapter/commit/9fb0ac2070fe2d6344e1d4197ab9d20cb135b7d0

ptype will be kept.
