### ISSUE TITLE
Please clarify maintenance status

### ISSUE THREAD

**Issue by rockstar** [casbin-rs/diesel-adapter#75]
This repository hasn't received any updates for more than a year. The current mainline depends on a version of diesel released more than three years ago, which also [has a RUSTSEC advisory and CVE connected with it](https://rustsec.org/advisories/RUSTSEC-2022-0090). My colleague, @peschkaj has tried to bring things up to date, but the CI is woefully unmaintained as well. It doesn't look like there is anyone on point to handle these sorts of issues and, for an authentication library, that's a bit concerning.

Can anyone clarify the status of this crate?

**Comment by PsiACE** [comment]
I'm sorry that the current state of being.

Although I am always mentioned, I do not have committer permissions on this repo. Also, I've been a little busy lately, so I'd be happy to return to this if I get a chance.

**Comment by pinkforest** [comment]
According to crates.io the ones who can publish there are @GopherJ and @hackerchai 

I wonder if you would be happy for people still use this crate ?

Perhaps looking for new maintainers could help things a bit with appropriate access or just publicly announce deprecation ?

**Comment by hsluoyz** [comment]
@rockstar @pinkforest we will actively find new contributors to continue maintaining these libs, will not deprecate. It's an open-source project. Any issue report or PRs are welcome to help us build it together.
