### ISSUE TITLE
`Connection` redefined here

### ISSUE THREAD

**Issue by einsli** [casbin-rs/diesel-adapter#87]
I want to user diesel-adapter， so I import by follow code
```toml
diesel-adapter = { version = "1.0.0", features = ["mysql"] }
```
when I use cargo build commnd, errors occured

```shell
/..../diesel-adapter-1.0.0/src/actions.rs:20:1
   |
18 | pub type Connection = diesel::PgConnection;
   | ------------------------------------------- previous definition of the type `Connection` here
19 | #[cfg(feature = "mysql")]
20 | pub type Connection = diesel::MysqlConnection;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Connection` redefined here
```

**Comment by hsluoyz** [comment]
@einsli did you notice they are different features? If you only use `mysql` feature, the other definitions won't be triggered

https://github.com/casbin-rs/diesel-adapter/blob/bfbb2dbb55c2039fe7f4fc3a71a2cdc292327e80/src/actions.rs#L17-L22
